#!/bin/bash
# PreToolUse hook: fires on every Bash call, but only acts on `gh issue view <n>` —
# the documented way an agent "fetches the relevant ticket" (see docs/agents/issue-tracker.md).
#
# When an agent is about to start work on a ticket, this:
#   1. Denies the call if another agent/human already claimed the ticket recently, so the
#      current agent picks a different one instead of duplicating work.
#   2. Otherwise self-assigns the issue and leaves a "starting work" comment, so any other
#      agent's hook run afterwards sees the claim and backs off.
#
# Safe to no-op: any failure (missing gh/jq, network, auth) falls through to a silent allow —
# this hook must never be the reason a ticket can't be fetched.
set -uo pipefail

CLAIM_MARKER_TEXT="🤖 Claude Code is starting work on this ticket"
CLAIM_WINDOW_HOURS=12

allow() {
  exit 0
}

deny() {
  local reason="$1"
  jq -n --arg reason "$reason" \
    '{hookSpecificOutput: {hookEventName: "PreToolUse", permissionDecision: "deny", permissionDecisionReason: $reason}}'
  exit 0
}

command -v jq >/dev/null 2>&1 || allow
command -v gh >/dev/null 2>&1 || allow

INPUT=$(cat)

TOOL_NAME=$(jq -r '.tool_name // empty' <<<"$INPUT")
[[ "$TOOL_NAME" == "Bash" ]] || allow

COMMAND=$(jq -r '.tool_input.command // empty' <<<"$INPUT")
SESSION_ID=$(jq -r '.session_id // empty' <<<"$INPUT")

[[ "$COMMAND" =~ gh[[:space:]]+issue[[:space:]]+view[[:space:]]+([0-9]+) ]] || allow
ISSUE_NUMBER="${BASH_REMATCH[1]}"
[[ -n "$SESSION_ID" ]] || allow

# Only claim once per session per issue — repeat `gh issue view` calls in the same
# session (re-reading a ticket) shouldn't re-assign or spam comments.
CLAIM_DIR="${TMPDIR:-/tmp}/claude-ticket-claims"
mkdir -p "$CLAIM_DIR" 2>/dev/null || allow
CLAIM_STAMP="$CLAIM_DIR/${SESSION_ID}-${ISSUE_NUMBER}"
[[ -f "$CLAIM_STAMP" ]] && allow

ISSUE_JSON=$(gh issue view "$ISSUE_NUMBER" --json number,state,assignees,comments 2>/dev/null) || allow

STATE=$(jq -r '.state // empty' <<<"$ISSUE_JSON")
[[ "$STATE" == "OPEN" ]] || allow

ME=$(gh api user --jq .login 2>/dev/null) || allow

# Case 1: someone else (human or another agent identity) is already an assignee.
OTHER_ASSIGNEES=$(jq -r --arg me "$ME" '[.assignees[]?.login | select(. != $me)] | join(", ")' <<<"$ISSUE_JSON")
if [[ -n "$OTHER_ASSIGNEES" ]]; then
  deny "Issue #$ISSUE_NUMBER is already assigned to $OTHER_ASSIGNEES. Pick a different ready-for-agent ticket to avoid duplicate work."
fi

# Case 2: a claim comment from a *different* session landed recently. Agents typically
# share one GitHub identity, so the assignee check alone can't distinguish two concurrent
# agent sessions — this catches that race. A window (not "forever") lets a ticket become
# claimable again if the prior session died without finishing.
CUTOFF=$(date -u -d "-${CLAIM_WINDOW_HOURS} hours" +%Y-%m-%dT%H:%M:%SZ 2>/dev/null)
if [[ -n "$CUTOFF" ]]; then
  RIVAL_CLAIM=$(jq -r --arg marker "$CLAIM_MARKER_TEXT" --arg sid "$SESSION_ID" --arg cutoff "$CUTOFF" '
    [.comments[]? | select(.body | contains($marker)) | select((.body | contains($sid)) | not) | select(.createdAt > $cutoff)] | length
  ' <<<"$ISSUE_JSON")
  if [[ "${RIVAL_CLAIM:-0}" -gt 0 ]]; then
    deny "Issue #$ISSUE_NUMBER already has a recent \"starting work\" comment from another session. Pick a different ready-for-agent ticket to avoid duplicate work."
  fi
fi

# Clear to claim: self-assign and leave a marker comment.
gh issue edit "$ISSUE_NUMBER" --add-assignee "@me" >/dev/null 2>&1

COMMENT_BODY="$CLAIM_MARKER_TEXT (session \`${SESSION_ID}\`).

Assigning to self to avoid duplicate work — if you're another agent picking up tickets, please check assignees and recent comments before starting on this one.

---
_Generated by [Claude Code](https://claude.ai/code)_"

gh issue comment "$ISSUE_NUMBER" --body "$COMMENT_BODY" >/dev/null 2>&1

touch "$CLAIM_STAMP" 2>/dev/null

allow
