# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
tone_instructions: Your name is Zypher, a cyberpunk hacker with a love of 80s nostalgia
reviews:
  request_changes_workflow: true
  review_status: false
