import { AttributeKey } from "#/lib/system/attributeKey.ts"
import { SkillCategory } from "#/lib/system/skillCategory.ts"
import { SkillGroupKey } from "#/lib/system/skillGroupKey.ts"
import { SpecializationKey } from "#/lib/system/specializationKey.ts"

export enum SkillKey {
  aronauticsMechanic = "Aronautics Mechanic",
  arcana = "Arcana",
  archery = "Archery",
  armorer = "Armorer",
  artisan = "Artisan",
  assensing = "Assensing",
  astralCombat = "Astral Combat",
  autoMechanic = "Auto Mechanic",
  automatics = "Automatics",
  banishing = "Banishing",
  binding = "Binding",
  blades = "Blades",
  chemistry = "Chemistry",
  climbing = "Climbing",
  clubs = "Clubs",
  compiling = "Compiling",
  computer = "Computer",
  con = "Con",
  counterspelling = "Counterspelling",
  cybercombat = "Cybercombat",
  cybertechnology = "Cybertechnology",
  dataSearch = "Data Search",
  demolitions = "Demolitions",
  disguise = "Disguise",
  diving = "Diving",
  dodge = "Dodge",
  electronicWarfare = "Electronic Warfare",
  enchanting = "Enchanting",
  escapeArtist = "Escape Artist",
  etiquette = "Etiquette",
  exoticMeleeWeapons = "Exotic Melee Weapons",
  exoticRangedWeapons = "Exotic Ranged Weapons",
  firstAid = "First Aid",
  forgery = "Forgery",
  gunnery = "Gunnery",
  gymnastics = "Gymnastics",
  hacking = "Hacking",
  hardware = "Hardware",
  heavyWeapons = "Heavy Weapons",
  industrialMechanic = "Industrial Mechanic",
  infiltration = "Infiltration",
  instruction = "Instruction",
  intimidation = "Intimidation",
  leadership = "Leadership",
  locksmith = "Locksmith",
  longarms = "Longarms",
  medicine = "Medicine",
  nauticalMechanic = "Nautical Mechanic",
  navigation = "Navigation",
  negotiation = "Negotiation",
  palming = "Palming",
  parachuting = "Parachuting",
  perception = "Perception",
  pilotAerospace = "Pilot Aerospace",
  pilotAircraft = "Pilot Aircraft",
  pilotAnthroform = "Pilot Anthroform",
  pilotExoticVehicle = "Pilot Exotic Vehicle",
  pilotGroundCraft = "Pilot Ground Craft",
  pilotWatercraft = "Pilot Watercraft",
  pistols = "Pistols",
  registering = "Registering",
  ritualSpellcasting = "Ritual Spellcasting",
  running = "Running",
  shadowing = "Shadowing",
  software = "Software",
  spellcasting = "Spellcasting",
  summoning = "Summoning",
  survival = "Survival",
  swimming = "Swimming",
  thrownWeapons = "Thrown Weapons",
  tracking = "Tracking",
  unarmedCombat = "Unarmed Combat",
}

export interface SkillInfo {
  attr: AttributeKey
  category: SkillCategory
  group?: SkillGroupKey
  isWeaponSkill?: boolean
  defaultable?: boolean

  /**
   * A list of available specializations for the skill.
   * Not the character's selected specialization
   */
  specializations?: SpecializationKey[]
}

export const skills: Record<SkillKey, SkillInfo> = {
  [SkillKey.aronauticsMechanic]: {
    attr: AttributeKey.logic,
    category: SkillCategory.Technical,
    group: SkillGroupKey.Mechanic,
    defaultable: false,
  },
  [SkillKey.arcana]: {
    attr: AttributeKey.logic,
    category: SkillCategory.Magic,
    defaultable: false,
  },
  [SkillKey.archery]: {
    attr: AttributeKey.agility,
    category: SkillCategory.Combat,
    specializations: [SpecializationKey.Bows, SpecializationKey.Crossbows],
  },
  [SkillKey.armorer]: {
    attr: AttributeKey.logic,
    category: SkillCategory.Technical,
    specializations: [SpecializationKey.FirearmsArmorer, SpecializationKey.MeleeArmorer, SpecializationKey.ExoticArmorer],
  },
  [SkillKey.artisan]: {
    attr: AttributeKey.intuition,
    category: SkillCategory.Technical,
    specializations: [SpecializationKey.Cooking, SpecializationKey.Drawing, SpecializationKey.Sculpting, SpecializationKey.Writing],
  },
  [SkillKey.assensing]: {
    attr: AttributeKey.intuition,
    category: SkillCategory.Magic,
    defaultable: false,
  },
  [SkillKey.astralCombat]: {
    attr: AttributeKey.willpower,
    category: SkillCategory.Magic,
    defaultable: false,
    specializations: [SpecializationKey.Weapon],
  },
  [SkillKey.autoMechanic]: {
    attr: AttributeKey.logic,
    category: SkillCategory.Technical,
    group: SkillGroupKey.Mechanic,
    defaultable: false,
  },
  [SkillKey.automatics]: {
    isWeaponSkill: true,
    attr: AttributeKey.agility,
    category: SkillCategory.Combat,
    group: SkillGroupKey.Firearms,
    specializations: [SpecializationKey.AssaultRifles, SpecializationKey.MachinePistols, SpecializationKey.SubmachineGuns],
  },
  [SkillKey.banishing]: {
    attr: AttributeKey.magic,
    category: SkillCategory.Magic,
    group: SkillGroupKey.Conjuring,
    defaultable: false,
    specializations: [
      SpecializationKey.EarthSpirit,
      SpecializationKey.FireSpirit,
      SpecializationKey.WaterSpirit,
      SpecializationKey.AirSpirit,
      SpecializationKey.BeastSpirit,
      SpecializationKey.ManSpirit,
      SpecializationKey.TaskSpirit,
    ],
  },
  [SkillKey.binding]: {
    attr: AttributeKey.magic,
    category: SkillCategory.Magic,
    group: SkillGroupKey.Conjuring,
    defaultable: false,
    specializations: [
      SpecializationKey.EarthSpirit,
      SpecializationKey.FireSpirit,
      SpecializationKey.WaterSpirit,
      SpecializationKey.AirSpirit,
      SpecializationKey.BeastSpirit,
      SpecializationKey.ManSpirit,
      SpecializationKey.TaskSpirit,
    ],
  },
  [SkillKey.blades]: {
    isWeaponSkill: true,
    attr: AttributeKey.agility,
    category: SkillCategory.Combat,
    group: SkillGroupKey.CloseCombat,
    specializations: [SpecializationKey.Axes, SpecializationKey.Knives, SpecializationKey.Swords],
  },
  [SkillKey.chemistry]: {
    attr: AttributeKey.logic,
    category: SkillCategory.Technical,
    specializations: [SpecializationKey.Biochemistry, SpecializationKey.Pharmaceuticals, SpecializationKey.Toxins],
  },
  [SkillKey.climbing]: {
    attr: AttributeKey.strength,
    category: SkillCategory.Physical,
    group: SkillGroupKey.Athletics,
    specializations: [SpecializationKey.Rappelling, SpecializationKey.RockClimbing],
  },
  [SkillKey.clubs]: {
    isWeaponSkill: true,
    attr: AttributeKey.agility,
    category: SkillCategory.Combat,
    group: SkillGroupKey.CloseCombat,
    specializations: [SpecializationKey.Batons, SpecializationKey.Hammers, SpecializationKey.Saps],
  },
  [SkillKey.compiling]: {
    attr: AttributeKey.resonance,
    category: SkillCategory.Resonance,
    group: SkillGroupKey.Tasking,
    defaultable: false,
    specializations: [
      SpecializationKey.CourierSprite,
      SpecializationKey.DataSprite,
      SpecializationKey.FaultSprite,
      SpecializationKey.MachineSprite,
      SpecializationKey.ScoutSprite,
    ],
  },
  [SkillKey.computer]: {
    attr: AttributeKey.logic,
    category: SkillCategory.Technical,
    group: SkillGroupKey.Electronics,
    specializations: [SpecializationKey.FaultFinding, SpecializationKey.MatrixSearch],
  },
  [SkillKey.con]: {
    attr: AttributeKey.charisma,
    category: SkillCategory.Social,
    group: SkillGroupKey.Influence,
    specializations: [SpecializationKey.FastTalk, SpecializationKey.Seduction],
  },
  [SkillKey.counterspelling]: {
    attr: AttributeKey.magic,
    category: SkillCategory.Magic,
    group: SkillGroupKey.Sorcery,
    defaultable: false,
    specializations: [
      SpecializationKey.CombatSpells,
      SpecializationKey.DetectionSpells,
      SpecializationKey.IllusionSpells,
      SpecializationKey.ManipulationSpells,
    ],
  },
  [SkillKey.cybercombat]: {
    attr: AttributeKey.logic,
    category: SkillCategory.Technical,
    group: SkillGroupKey.Cracking,
    specializations: [SpecializationKey.CrashPrograms, SpecializationKey.DataBombs],
  },
  [SkillKey.cybertechnology]: {
    attr: AttributeKey.logic,
    category: SkillCategory.Technical,
    group: SkillGroupKey.Biotech,
    defaultable: false,
    specializations: [SpecializationKey.Bodyware, SpecializationKey.Cyberware, SpecializationKey.Headware],
  },
  [SkillKey.dataSearch]: {
    attr: AttributeKey.logic,
    category: SkillCategory.Technical,
    group: SkillGroupKey.Electronics,
    specializations: [SpecializationKey.MatrixSearch],
  },
  [SkillKey.demolitions]: {
    attr: AttributeKey.logic,
    category: SkillCategory.Technical,
    specializations: [SpecializationKey.Defusing, SpecializationKey.Placement, SpecializationKey.RemoteDetonation],
  },
  [SkillKey.disguise]: {
    attr: AttributeKey.intuition,
    category: SkillCategory.Physical,
    group: SkillGroupKey.Stealth,
    specializations: [SpecializationKey.Costuming, SpecializationKey.Makeup, SpecializationKey.Masks],
  },
  [SkillKey.diving]: {
    attr: AttributeKey.body,
    category: SkillCategory.Physical,
    specializations: [SpecializationKey.FreeDiving, SpecializationKey.Scuba],
  },
  [SkillKey.dodge]: {
    attr: AttributeKey.reaction,
    category: SkillCategory.Physical,
  },
  [SkillKey.electronicWarfare]: {
    attr: AttributeKey.logic,
    category: SkillCategory.Technical,
    group: SkillGroupKey.Cracking,
    defaultable: false,
    specializations: [SpecializationKey.Communications, SpecializationKey.Radar, SpecializationKey.Sensor],
  },
  [SkillKey.enchanting]: {
    attr: AttributeKey.magic,
    category: SkillCategory.Magic,
    defaultable: false,
  },
  [SkillKey.escapeArtist]: {
    attr: AttributeKey.agility,
    category: SkillCategory.Physical,
    specializations: [SpecializationKey.Cuffs, SpecializationKey.Ropes],
  },
  [SkillKey.etiquette]: {
    attr: AttributeKey.charisma,
    category: SkillCategory.Social,
    group: SkillGroupKey.Influence,
    specializations: [
      SpecializationKey.Corporate,
      SpecializationKey.Gangs,
      SpecializationKey.Mafia,
      SpecializationKey.Street,
      SpecializationKey.Tribal,
      SpecializationKey.Yakuza,
    ],
  },
  [SkillKey.exoticMeleeWeapons]: {
    isWeaponSkill: true,
    attr: AttributeKey.agility,
    category: SkillCategory.Combat,
  },
  [SkillKey.exoticRangedWeapons]: {
    isWeaponSkill: true,
    attr: AttributeKey.agility,
    category: SkillCategory.Combat,
  },
  [SkillKey.firstAid]: {
    attr: AttributeKey.logic,
    category: SkillCategory.Technical,
    group: SkillGroupKey.Biotech,
    specializations: [SpecializationKey.GunshotWounds, SpecializationKey.Trauma],
  },
  [SkillKey.forgery]: {
    attr: AttributeKey.agility,
    category: SkillCategory.Technical,
    specializations: [SpecializationKey.DataManipulation, SpecializationKey.PrintedMaterials],
  },
  [SkillKey.gunnery]: {
    isWeaponSkill: true,
    attr: AttributeKey.agility,
    category: SkillCategory.Combat,
    specializations: [SpecializationKey.Ballistic, SpecializationKey.Energy, SpecializationKey.GuidedMissiles],
  },
  [SkillKey.gymnastics]: {
    attr: AttributeKey.agility,
    category: SkillCategory.Physical,
    group: SkillGroupKey.Athletics,
    specializations: [SpecializationKey.Balance, SpecializationKey.BrakingFall, SpecializationKey.Dodge, SpecializationKey.Jumping, SpecializationKey.Rolling],
  },
  [SkillKey.hacking]: {
    attr: AttributeKey.logic,
    category: SkillCategory.Technical,
    group: SkillGroupKey.Cracking,
    specializations: [SpecializationKey.Exploit, SpecializationKey.Spoof],
  },
  [SkillKey.hardware]: {
    attr: AttributeKey.logic,
    category: SkillCategory.Technical,
    group: SkillGroupKey.Electronics,
    defaultable: false,
    specializations: [SpecializationKey.Commlinks, SpecializationKey.SecuritySystems, SpecializationKey.WeaponsHardware],
  },
  [SkillKey.heavyWeapons]: {
    isWeaponSkill: true,
    attr: AttributeKey.agility,
    category: SkillCategory.Combat,
    specializations: [SpecializationKey.AssaultCannons, SpecializationKey.GrenadeLaunchers, SpecializationKey.MachineGuns, SpecializationKey.RocketLaunchers],
  },
  [SkillKey.industrialMechanic]: {
    attr: AttributeKey.logic,
    category: SkillCategory.Technical,
    group: SkillGroupKey.Mechanic,
    defaultable: false,
  },
  [SkillKey.infiltration]: {
    attr: AttributeKey.agility,
    category: SkillCategory.Physical,
    group: SkillGroupKey.Stealth,
    specializations: [SpecializationKey.Building, SpecializationKey.Urban, SpecializationKey.Wilderness],
  },
  [SkillKey.instruction]: {
    attr: AttributeKey.charisma,
    category: SkillCategory.Social,
  },
  [SkillKey.intimidation]: {
    attr: AttributeKey.charisma,
    category: SkillCategory.Social,
    specializations: [SpecializationKey.Mental, SpecializationKey.Physical],
  },
  [SkillKey.leadership]: {
    attr: AttributeKey.charisma,
    category: SkillCategory.Social,
    group: SkillGroupKey.Influence,
    specializations: [SpecializationKey.Command, SpecializationKey.Direct, SpecializationKey.Rally],
  },
  [SkillKey.locksmith]: {
    attr: AttributeKey.agility,
    category: SkillCategory.Technical,
    specializations: [SpecializationKey.CombinationLocks, SpecializationKey.ElectronicLocks, SpecializationKey.MechanicalLocks],
  },
  [SkillKey.longarms]: {
    isWeaponSkill: true,
    attr: AttributeKey.agility,
    category: SkillCategory.Combat,
    group: SkillGroupKey.Firearms,
    specializations: [SpecializationKey.Rifles, SpecializationKey.Shotguns, SpecializationKey.SniperRifles],
  },
  [SkillKey.medicine]: {
    attr: AttributeKey.logic,
    category: SkillCategory.Technical,
    group: SkillGroupKey.Biotech,
    defaultable: false,
    specializations: [SpecializationKey.Diagnostics, SpecializationKey.TraumaSurgery],
  },
  [SkillKey.nauticalMechanic]: {
    attr: AttributeKey.logic,
    category: SkillCategory.Technical,
    group: SkillGroupKey.Mechanic,
    defaultable: false,
  },
  [SkillKey.navigation]: {
    attr: AttributeKey.intuition,
    category: SkillCategory.Physical,
    group: SkillGroupKey.Outdoors,
    specializations: [SpecializationKey.Celestial, SpecializationKey.GPS, SpecializationKey.Landmarks, SpecializationKey.Maps],
  },
  [SkillKey.negotiation]: {
    attr: AttributeKey.charisma,
    category: SkillCategory.Social,
    group: SkillGroupKey.Influence,
    specializations: [SpecializationKey.Bargaining, SpecializationKey.Contracts, SpecializationKey.Diplomacy],
  },
  [SkillKey.palming]: {
    attr: AttributeKey.agility,
    category: SkillCategory.Physical,
    group: SkillGroupKey.Stealth,
    specializations: [SpecializationKey.Pickpocketing],
  },
  [SkillKey.parachuting]: {
    attr: AttributeKey.body,
    category: SkillCategory.Physical,
    specializations: [SpecializationKey.BASEJumping, SpecializationKey.Freefalling],
  },
  [SkillKey.perception]: {
    attr: AttributeKey.intuition,
    category: SkillCategory.Physical,
    specializations: [SpecializationKey.Hearing, SpecializationKey.Scent, SpecializationKey.Sight, SpecializationKey.Touch],
  },
  [SkillKey.pilotAerospace]: {
    attr: AttributeKey.reaction,
    category: SkillCategory.Vehicle,
    defaultable: false,
    specializations: [SpecializationKey.Shuttle, SpecializationKey.SpaceStation],
  },
  [SkillKey.pilotAircraft]: {
    attr: AttributeKey.reaction,
    category: SkillCategory.Vehicle,
    defaultable: false,
    specializations: [SpecializationKey.FixedWing, SpecializationKey.Rotorcraft, SpecializationKey.VTOL],
  },
  [SkillKey.pilotAnthroform]: {
    attr: AttributeKey.reaction,
    category: SkillCategory.Vehicle,
    defaultable: false,
    specializations: [SpecializationKey.Drone],
  },
  [SkillKey.pilotExoticVehicle]: {
    attr: AttributeKey.reaction,
    category: SkillCategory.Vehicle,
    defaultable: false,
  },
  [SkillKey.pilotGroundCraft]: {
    attr: AttributeKey.reaction,
    category: SkillCategory.Vehicle,
    specializations: [SpecializationKey.RemoteControl, SpecializationKey.Wheeled],
  },
  [SkillKey.pilotWatercraft]: {
    attr: AttributeKey.reaction,
    category: SkillCategory.Vehicle,
    specializations: [SpecializationKey.Motorboat, SpecializationKey.Sailboat, SpecializationKey.Ships],
  },
  [SkillKey.pistols]: {
    isWeaponSkill: true,
    attr: AttributeKey.agility,
    category: SkillCategory.Combat,
    group: SkillGroupKey.Firearms,
    specializations: [SpecializationKey.HeavyPistols, SpecializationKey.HoldOutPistols, SpecializationKey.SemiAutomatic],
  },
  [SkillKey.registering]: {
    attr: AttributeKey.resonance,
    category: SkillCategory.Resonance,
    group: SkillGroupKey.Tasking,
    defaultable: false,
    specializations: [
      SpecializationKey.CourierSprite,
      SpecializationKey.DataSprite,
      SpecializationKey.FaultSprite,
      SpecializationKey.MachineSprite,
      SpecializationKey.ScoutSprite,
    ],
  },
  [SkillKey.ritualSpellcasting]: {
    attr: AttributeKey.magic,
    category: SkillCategory.Magic,
    group: SkillGroupKey.Sorcery,
    defaultable: false,
  },
  [SkillKey.running]: {
    attr: AttributeKey.strength,
    category: SkillCategory.Physical,
    group: SkillGroupKey.Athletics,
    specializations: [SpecializationKey.Distance, SpecializationKey.Sprint],
  },
  [SkillKey.shadowing]: {
    attr: AttributeKey.intuition,
    category: SkillCategory.Physical,
    group: SkillGroupKey.Stealth,
    specializations: [SpecializationKey.Foot, SpecializationKey.Vehicle],
  },
  [SkillKey.software]: {
    attr: AttributeKey.logic,
    category: SkillCategory.Technical,
    group: SkillGroupKey.Electronics,
    defaultable: false,
    specializations: [SpecializationKey.Agents, SpecializationKey.Viruses],
  },
  [SkillKey.spellcasting]: {
    attr: AttributeKey.magic,
    category: SkillCategory.Magic,
    group: SkillGroupKey.Sorcery,
    defaultable: false,
    specializations: [
      SpecializationKey.CombatSpells,
      SpecializationKey.DetectionSpells,
      SpecializationKey.IllusionSpells,
      SpecializationKey.ManipulationSpells,
    ],
  },
  [SkillKey.summoning]: {
    attr: AttributeKey.magic,
    category: SkillCategory.Magic,
    group: SkillGroupKey.Conjuring,
    defaultable: false,
    specializations: [
      SpecializationKey.EarthSpirit,
      SpecializationKey.FireSpirit,
      SpecializationKey.WaterSpirit,
      SpecializationKey.AirSpirit,
      SpecializationKey.BeastSpirit,
      SpecializationKey.ManSpirit,
      SpecializationKey.TaskSpirit,
    ],
  },
  [SkillKey.survival]: {
    attr: AttributeKey.willpower,
    category: SkillCategory.Physical,
    group: SkillGroupKey.Outdoors,
    specializations: [SpecializationKey.Arctic, SpecializationKey.Desert, SpecializationKey.Temperate, SpecializationKey.Tropical],
  },
  [SkillKey.swimming]: {
    attr: AttributeKey.strength,
    category: SkillCategory.Physical,
    group: SkillGroupKey.Athletics,
    specializations: [SpecializationKey.Crawl, SpecializationKey.Freestyle],
  },
  [SkillKey.thrownWeapons]: {
    isWeaponSkill: true,
    attr: AttributeKey.agility,
    category: SkillCategory.Combat,
    specializations: [SpecializationKey.ThrownBlades, SpecializationKey.Grenades, SpecializationKey.NonExplosive],
  },
  [SkillKey.tracking]: {
    attr: AttributeKey.intuition,
    category: SkillCategory.Physical,
    group: SkillGroupKey.Outdoors,
    specializations: [SpecializationKey.Urban, SpecializationKey.Wilderness],
  },
  [SkillKey.unarmedCombat]: {
    isWeaponSkill: true,
    attr: AttributeKey.agility,
    category: SkillCategory.Combat,
    group: SkillGroupKey.CloseCombat,
    specializations: [SpecializationKey.Blocking, SpecializationKey.Kickboxing, SpecializationKey.MartialArts, SpecializationKey.Subduing],
  },
}
