export enum FirearmTypeKey {
  taser = "taser",
  holdout = "holdout",
  lightPistol = "light pistol",
  heavyPistol = "heavy pistol",
  machinePistol = "machine pistol",
  smg = "submachine gun",
  assaultRifle = "assault rifle",
  sportRifle = "sport rifle",
  sniperRifle = "sniper rifle",
  shotgun = "shotgun",
  shotgunFlechette = "shotgun-flechette",
  shotgunSlug = "shotgun-slug",
  exoitic = "exoitic",
  lmg = "light machine gun",
  mmg = "medium machine gun",
  hmg = "heavy machine gun",
  grenadeLauncher = "grenade launcher",
  assultCannon = "assault cannon",
  missleLauncher = "missile launcher",
}
