/**
 * 250 randomly generated full names, used to suggest a cover identity when
 * creating a fake SIN. Generated once with @faker-js/faker.
 */
export const SinNameList: readonly string[] = [
  "Abigale Cummings",
  "Albert Harris",
  "Alejandrin Stamm",
  "Alex Johnston",
  "Alexa Kub",
  "Alexis McClure IV",
  "Alyssa Greenfelder",
  "Alysson Ortiz",
  "Amber McClure",
  "Amy Schaden",
  "Ana Schumm",
  "Anastasia Steuber",
  "Andrea Steuber-Hirthe",
  "Andres Braun",
  "Andy Abshire",
  "Angus Howe DVM",
  "Annabelle Howe DVM",
  "Arturo Buckridge",
  "Arturo Corwin",
  "Ashley Gibson",
  "Ashley Raynor",
  "Audie Luettgen",
  "Aurelio Daugherty",
  "Bailee Feest",
  "Barry Abshire",
  "Beth Wintheiser",
  "Betty Kuhn",
  "Beulah Sauer",
  "Beverly Cassin",
  "Billy Lesch",
  "Birdie Bruen",
  "Bobby Dietrich",
  "Bradley Lindgren",
  "Braxton Funk",
  "Brett Heller",
  "Brian Lindgren",
  "Brionna O'Conner-Boyer",
  "Bryant Renner",
  "Byron Trantow",
  "Cathy Jacobs",
  "Cecil Barrows",
  "Cecilia Collins",
  "Christie Breitenberg",
  "Christina Gorczany",
  "Clayton Hackett",
  "Colin O'Hara",
  "Crystal Dooley",
  "Damian Ruecker-Considine",
  "Darin Reichert",
  "Darryl Hickle",
  "Dawn Smith DDS",
  "Dean Hagenes IV",
  "Dereck Krajcik",
  "Derrick Murray",
  "Devin Tromp",
  "Dolores Johns",
  "Doreen Kuhlman V",
  "Dr. Allison Barrows III",
  "Dr. Beth Herman",
  "Dr. Elenora Casper",
  "Dr. Eloisa Treutel",
  "Dr. Erick Ferry",
  "Dr. Iris Hodkiewicz",
  "Dr. Marvin Hintz",
  "Dr. Megane Ankunding",
  "Dr. Murray Haag",
  "Dr. Roland Howe",
  "Dustin Jenkins",
  "Earlene Kris",
  "Ed Stokes",
  "Eddie Herzog",
  "Edgar Mueller",
  "Edmond Glover",
  "Edward Corkery",
  "Edwardo Kilback",
  "Elijah Schiller",
  "Elizabeth Jaskolski",
  "Elliott Wuckert V",
  "Ellis Wuckert",
  "Elody Brown",
  "Emelia Green",
  "Emile Block",
  "Emmett Mann",
  "Eric Feest",
  "Erma Muller",
  "Erma Parisian",
  "Ervin Cartwright",
  "Fannie Green",
  "Felix Kutch",
  "Forest Orn",
  "Francisco Terry",
  "Fredrick Bailey",
  "Gardner Harber",
  "Garnet Williamson",
  "Garrett Bailey",
  "Garrick Hudson-Schoen",
  "George Klocko",
  "Gertrude Shanahan",
  "Granville Nitzsche",
  "Griffin Carroll",
  "Guillermo Kautzer",
  "Gust Littel",
  "Hailee O'Conner",
  "Hailee Schmidt",
  "Hannah Kuvalis",
  "Heidi Schowalter",
  "Helen Grimes",
  "Helmer Gottlieb",
  "Henriette Abernathy",
  "Herman Hand",
  "Hermina Armstrong-Dietrich",
  "Hobart Vandervort",
  "Immanuel Senger",
  "Ines DuBuque",
  "Isabell Hodkiewicz",
  "Israel Romaguera",
  "Ivan Weissnat",
  "James Mayer",
  "Jana Marvin-Labadie",
  "Jaquan Koelpin Jr.",
  "Jasmine Maggio-Mosciski",
  "Jason White",
  "Jay Hermiston",
  "Jeanne Conroy",
  "Jeannette Skiles",
  "Jennyfer Aufderhar",
  "Jerald Schmidt",
  "Jerome Cormier",
  "Jessica Rowe",
  "Johnathan Bailey PhD",
  "Jordane Bergstrom Jr.",
  "Joseph Becker",
  "Julianne Roob",
  "Kamryn Barrows",
  "Karelle Hegmann MD",
  "Katharina O'Conner",
  "Keeley Hartmann Jr.",
  "Keith Schiller",
  "Kelton Halvorson",
  "Kenneth Braun DVM",
  "Kent Kunze I",
  "Kevin Waters",
  "Kieran Russel",
  "Krista Nitzsche",
  "Larry Kuhlman",
  "Laura Wisozk I",
  "Lea Boehm",
  "Lenore Harvey",
  "Leopoldo Borer",
  "Liliane Gorczany",
  "Lilliana Powlowski II",
  "Lindsay Kertzmann",
  "Lloyd Boehm",
  "Lonnie Schinner",
  "Lourdes Wisozk",
  "Lucia Hegmann DDS",
  "Luciano Greenfelder",
  "Lucile Wuckert",
  "Lucious Kub",
  "Mandy Emard",
  "Marcos Harris",
  "Margaret Thiel V",
  "Margarita Beahan",
  "Mariah Gusikowski",
  "Marian Hodkiewicz",
  "Marina Feest",
  "Marisa Tillman",
  "Marsha Kertzmann",
  "Martin Bartoletti",
  "Matilde Kuhn DVM",
  "Maurice Torp PhD",
  "Mavis Huel",
  "May Homenick",
  "Maya Gerlach I",
  "Meghan Hermann",
  "Meredith Greenfelder",
  "Meredith Shanahan-Lockman",
  "Miss Christy Wunsch-Auer",
  "Miss Tracey Kuvalis PhD",
  "Mr. Alexandrea Adams",
  "Mr. Brad Hudson",
  "Mr. Carl Bergstrom Sr.",
  "Mr. Chandler Kuhic",
  "Mr. Ed Christiansen",
  "Mr. Francisco Daniel",
  "Mr. Hayden Kutch I",
  "Mr. Katelynn Stehr",
  "Mr. Mallie Powlowski",
  "Mr. Ronald Sawayn",
  "Mr. Syble O'Connell",
  "Mr. Tomas Denesik",
  "Mrs. Carla Emard",
  "Mrs. Delia Runolfsdottir DDS",
  "Mrs. Hardy Torp",
  "Mrs. Kay Quigley",
  "Mrs. Margie Rowe",
  "Mrs. Otho Klein-Roob",
  "Mrs. Sheila Doyle",
  "Ms. Janis Tremblay",
  "Ms. Nedra Friesen",
  "Murray Hills I",
  "Nancy Balistreri",
  "Neil Baumbach Sr.",
  "Nelson Stiedemann",
  "Neoma Heathcote-Reinger",
  "Neoma Kemmer",
  "Nicholas Hyatt",
  "Noe Legros",
  "Okey Ondricka",
  "Omar Cole IV",
  "Oswaldo Gulgowski-Balistreri",
  "Penny Fahey",
  "Pinkie Lesch",
  "Ressie Beatty-Kihn V",
  "Rhea Bechtelar",
  "Richard Balistreri",
  "Roberto Blanda",
  "Rosanna Dietrich",
  "Roselyn Zemlak",
  "Rosendo Klein",
  "Rubye Collier",
  "Rudolph Konopelski",
  "Rylee Bradtke",
  "Sabina Nader",
  "Santos Franecki",
  "Scotty Donnelly",
  "Sean Pfeffer",
  "Shanon Gutmann",
  "Sonia Beatty",
  "Sunny Harris",
  "Sylvester Runolfsdottir",
  "Taylor Mraz",
  "Teagan Willms",
  "Terrell Bauch",
  "Thora Beier",
  "Tiana Cronin",
  "Tomas Lindgren",
  "Toney Bahringer",
  "Tressa Koelpin",
  "Tyree Thompson",
  "Van Pouros",
  "Vickie Metz",
  "Virgil Armstrong",
  "Vivien Leffler",
  "Wayne Hills MD",
  "Winfield Graham",
  "Winifred Stroman",
  "Wm Stokes-Blick",
  "Zelma Herman",
  "Zena Pacocha",
]
