// Generates the static name list consumed by `sinUtils.ts` for the "Randomize
// name" button on the SIN form. Run `yarn generate:sin-names` to regenerate.
import { faker } from "@faker-js/faker"
import { writeFileSync } from "node:fs"
import path from "node:path"
import { fileURLToPath } from "node:url"

const NAME_COUNT = 250
const SEED = 90210

faker.seed(SEED)

const names = new Set()
while (names.size < NAME_COUNT) {
  names.add(faker.person.fullName())
}

const sortedNames = [...names].sort((a, b) => a.localeCompare(b))

const outFile = path.join(
  path.dirname(fileURLToPath(import.meta.url)),
  "../src/system/gear/sinNameList.ts",
)

const fileContents = `/**
 * ${NAME_COUNT} randomly generated full names, used to suggest a cover
 * identity when creating a fake SIN. Generated by \`scripts/generateSinNames.mjs\`
 * (\`yarn generate:sin-names\`) using @faker-js/faker with seed ${SEED}.
 */
export const SinNameList: readonly string[] = [
${sortedNames.map((name) => `  ${JSON.stringify(name)},`).join("\n")}
]
`

writeFileSync(outFile, fileContents)

console.log(`Wrote ${sortedNames.length} names to ${outFile}`)
