/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RunnerIdRouteImport } from './routes/$runnerId'
import { Route as RunnerIdDetailsRouteImport } from './routes/$runnerId/_details'
import { Route as RunnerIdViewerRouteImport } from './routes/$runnerId/_viewer'
import { Route as EditRunnerIdRouteImport } from './routes/edit/$runnerId'
import { Route as GmIndexRouteImport } from './routes/gm/index'
import { Route as GmEncounterBuilderRouteImport } from './routes/gm/encounter-builder'
import { Route as GmInitiativeTrackerRouteImport } from './routes/gm/initiative-tracker'
import { Route as GmNpcBuilderRouteImport } from './routes/gm/npc-builder'
import { Route as NewIndexRouteImport } from './routes/new/index'
import { Route as TestIndexRouteImport } from './routes/test/index'
import { Route as RunnerIdViewerIndexRouteImport } from './routes/$runnerId/_viewer/index'
import { Route as RunnerIdViewerAboutRouteImport } from './routes/$runnerId/_viewer/about'
import { Route as RunnerIdViewerAdeptPowersRouteImport } from './routes/$runnerId/_viewer/adept-powers'
import { Route as RunnerIdViewerComplexFormsRouteImport } from './routes/$runnerId/_viewer/complex-forms'
import { Route as RunnerIdViewerContactsRouteImport } from './routes/$runnerId/_viewer/contacts'
import { Route as RunnerIdViewerDefenseRouteImport } from './routes/$runnerId/_viewer/defense'
import { Route as RunnerIdViewerDronesRouteImport } from './routes/$runnerId/_viewer/drones'
import { Route as RunnerIdViewerFinancesRouteImport } from './routes/$runnerId/_viewer/finances'
import { Route as RunnerIdViewerGearRouteImport } from './routes/$runnerId/_viewer/gear'
import { Route as RunnerIdViewerLicensesRouteImport } from './routes/$runnerId/_viewer/licenses'
import { Route as RunnerIdViewerMatrixRouteImport } from './routes/$runnerId/_viewer/matrix'
import { Route as RunnerIdViewerNotesRouteImport } from './routes/$runnerId/_viewer/notes'
import { Route as RunnerIdViewerOffenseRouteImport } from './routes/$runnerId/_viewer/offense'
import { Route as RunnerIdViewerPowersRouteImport } from './routes/$runnerId/_viewer/powers'
import { Route as RunnerIdViewerSkillsRouteImport } from './routes/$runnerId/_viewer/skills'
import { Route as RunnerIdViewerSpellsRouteImport } from './routes/$runnerId/_viewer/spells'
import { Route as RunnerIdViewerSpiritsRouteImport } from './routes/$runnerId/_viewer/spirits'
import { Route as RunnerIdViewerSpritesRouteImport } from './routes/$runnerId/_viewer/sprites'
import { Route as RunnerIdViewerVehiclesRouteImport } from './routes/$runnerId/_viewer/vehicles'
import { Route as TestEntityCardAllRouteImport } from './routes/test/entityCard/all'
import { Route as TestEntityCardMigratedItemCardsRouteImport } from './routes/test/entityCard/migratedItemCards'
import { Route as TestThemeTypographyRouteImport } from './routes/test/theme/typography'
import { Route as RunnerIdDetailsItemItemIdRouteImport } from './routes/$runnerId/_details/item.$itemId'
import { Route as TestItemsDetailsAllRouteImport } from './routes/test/items/details.all'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RunnerIdRoute = RunnerIdRouteImport.update({
  id: '/$runnerId',
  path: '/$runnerId',
  getParentRoute: () => rootRouteImport,
} as any)
const RunnerIdDetailsRoute = RunnerIdDetailsRouteImport.update({
  id: '/_details',
  getParentRoute: () => RunnerIdRoute,
} as any)
const RunnerIdViewerRoute = RunnerIdViewerRouteImport.update({
  id: '/_viewer',
  getParentRoute: () => RunnerIdRoute,
} as any)
const EditRunnerIdRoute = EditRunnerIdRouteImport.update({
  id: '/edit/$runnerId',
  path: '/edit/$runnerId',
  getParentRoute: () => rootRouteImport,
} as any)
const GmIndexRoute = GmIndexRouteImport.update({
  id: '/gm/',
  path: '/gm/',
  getParentRoute: () => rootRouteImport,
} as any)
const GmEncounterBuilderRoute = GmEncounterBuilderRouteImport.update({
  id: '/gm/encounter-builder',
  path: '/gm/encounter-builder',
  getParentRoute: () => rootRouteImport,
} as any)
const GmInitiativeTrackerRoute = GmInitiativeTrackerRouteImport.update({
  id: '/gm/initiative-tracker',
  path: '/gm/initiative-tracker',
  getParentRoute: () => rootRouteImport,
} as any)
const GmNpcBuilderRoute = GmNpcBuilderRouteImport.update({
  id: '/gm/npc-builder',
  path: '/gm/npc-builder',
  getParentRoute: () => rootRouteImport,
} as any)
const NewIndexRoute = NewIndexRouteImport.update({
  id: '/new/',
  path: '/new/',
  getParentRoute: () => rootRouteImport,
} as any)
const TestIndexRoute = TestIndexRouteImport.update({
  id: '/test/',
  path: '/test/',
  getParentRoute: () => rootRouteImport,
} as any)
const RunnerIdViewerIndexRoute = RunnerIdViewerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RunnerIdViewerRoute,
} as any)
const RunnerIdViewerAboutRoute = RunnerIdViewerAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => RunnerIdViewerRoute,
} as any)
const RunnerIdViewerAdeptPowersRoute =
  RunnerIdViewerAdeptPowersRouteImport.update({
    id: '/adept-powers',
    path: '/adept-powers',
    getParentRoute: () => RunnerIdViewerRoute,
  } as any)
const RunnerIdViewerComplexFormsRoute =
  RunnerIdViewerComplexFormsRouteImport.update({
    id: '/complex-forms',
    path: '/complex-forms',
    getParentRoute: () => RunnerIdViewerRoute,
  } as any)
const RunnerIdViewerContactsRoute = RunnerIdViewerContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => RunnerIdViewerRoute,
} as any)
const RunnerIdViewerDefenseRoute = RunnerIdViewerDefenseRouteImport.update({
  id: '/defense',
  path: '/defense',
  getParentRoute: () => RunnerIdViewerRoute,
} as any)
const RunnerIdViewerDronesRoute = RunnerIdViewerDronesRouteImport.update({
  id: '/drones',
  path: '/drones',
  getParentRoute: () => RunnerIdViewerRoute,
} as any)
const RunnerIdViewerFinancesRoute = RunnerIdViewerFinancesRouteImport.update({
  id: '/finances',
  path: '/finances',
  getParentRoute: () => RunnerIdViewerRoute,
} as any)
const RunnerIdViewerGearRoute = RunnerIdViewerGearRouteImport.update({
  id: '/gear',
  path: '/gear',
  getParentRoute: () => RunnerIdViewerRoute,
} as any)
const RunnerIdViewerLicensesRoute = RunnerIdViewerLicensesRouteImport.update({
  id: '/licenses',
  path: '/licenses',
  getParentRoute: () => RunnerIdViewerRoute,
} as any)
const RunnerIdViewerMatrixRoute = RunnerIdViewerMatrixRouteImport.update({
  id: '/matrix',
  path: '/matrix',
  getParentRoute: () => RunnerIdViewerRoute,
} as any)
const RunnerIdViewerNotesRoute = RunnerIdViewerNotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => RunnerIdViewerRoute,
} as any)
const RunnerIdViewerOffenseRoute = RunnerIdViewerOffenseRouteImport.update({
  id: '/offense',
  path: '/offense',
  getParentRoute: () => RunnerIdViewerRoute,
} as any)
const RunnerIdViewerPowersRoute = RunnerIdViewerPowersRouteImport.update({
  id: '/powers',
  path: '/powers',
  getParentRoute: () => RunnerIdViewerRoute,
} as any)
const RunnerIdViewerSkillsRoute = RunnerIdViewerSkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => RunnerIdViewerRoute,
} as any)
const RunnerIdViewerSpellsRoute = RunnerIdViewerSpellsRouteImport.update({
  id: '/spells',
  path: '/spells',
  getParentRoute: () => RunnerIdViewerRoute,
} as any)
const RunnerIdViewerSpiritsRoute = RunnerIdViewerSpiritsRouteImport.update({
  id: '/spirits',
  path: '/spirits',
  getParentRoute: () => RunnerIdViewerRoute,
} as any)
const RunnerIdViewerSpritesRoute = RunnerIdViewerSpritesRouteImport.update({
  id: '/sprites',
  path: '/sprites',
  getParentRoute: () => RunnerIdViewerRoute,
} as any)
const RunnerIdViewerVehiclesRoute = RunnerIdViewerVehiclesRouteImport.update({
  id: '/vehicles',
  path: '/vehicles',
  getParentRoute: () => RunnerIdViewerRoute,
} as any)
const TestEntityCardAllRoute = TestEntityCardAllRouteImport.update({
  id: '/test/entityCard/all',
  path: '/test/entityCard/all',
  getParentRoute: () => rootRouteImport,
} as any)
const TestEntityCardMigratedItemCardsRoute =
  TestEntityCardMigratedItemCardsRouteImport.update({
    id: '/test/entityCard/migratedItemCards',
    path: '/test/entityCard/migratedItemCards',
    getParentRoute: () => rootRouteImport,
  } as any)
const TestThemeTypographyRoute = TestThemeTypographyRouteImport.update({
  id: '/test/theme/typography',
  path: '/test/theme/typography',
  getParentRoute: () => rootRouteImport,
} as any)
const RunnerIdDetailsItemItemIdRoute =
  RunnerIdDetailsItemItemIdRouteImport.update({
    id: '/item/$itemId',
    path: '/item/$itemId',
    getParentRoute: () => RunnerIdDetailsRoute,
  } as any)
const TestItemsDetailsAllRoute = TestItemsDetailsAllRouteImport.update({
  id: '/test/items/details/all',
  path: '/test/items/details/all',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$runnerId': typeof RunnerIdRouteWithChildren
  '/edit/$runnerId': typeof EditRunnerIdRoute
  '/gm/encounter-builder': typeof GmEncounterBuilderRoute
  '/gm/initiative-tracker': typeof GmInitiativeTrackerRoute
  '/gm/npc-builder': typeof GmNpcBuilderRoute
  '/gm/': typeof GmIndexRoute
  '/new/': typeof NewIndexRoute
  '/test/': typeof TestIndexRoute
  '/$runnerId/about': typeof RunnerIdViewerAboutRoute
  '/$runnerId/adept-powers': typeof RunnerIdViewerAdeptPowersRoute
  '/$runnerId/complex-forms': typeof RunnerIdViewerComplexFormsRoute
  '/$runnerId/contacts': typeof RunnerIdViewerContactsRoute
  '/$runnerId/defense': typeof RunnerIdViewerDefenseRoute
  '/$runnerId/drones': typeof RunnerIdViewerDronesRoute
  '/$runnerId/finances': typeof RunnerIdViewerFinancesRoute
  '/$runnerId/gear': typeof RunnerIdViewerGearRoute
  '/$runnerId/licenses': typeof RunnerIdViewerLicensesRoute
  '/$runnerId/matrix': typeof RunnerIdViewerMatrixRoute
  '/$runnerId/notes': typeof RunnerIdViewerNotesRoute
  '/$runnerId/offense': typeof RunnerIdViewerOffenseRoute
  '/$runnerId/powers': typeof RunnerIdViewerPowersRoute
  '/$runnerId/skills': typeof RunnerIdViewerSkillsRoute
  '/$runnerId/spells': typeof RunnerIdViewerSpellsRoute
  '/$runnerId/spirits': typeof RunnerIdViewerSpiritsRoute
  '/$runnerId/sprites': typeof RunnerIdViewerSpritesRoute
  '/$runnerId/vehicles': typeof RunnerIdViewerVehiclesRoute
  '/test/entityCard/all': typeof TestEntityCardAllRoute
  '/test/entityCard/migratedItemCards': typeof TestEntityCardMigratedItemCardsRoute
  '/test/theme/typography': typeof TestThemeTypographyRoute
  '/$runnerId/': typeof RunnerIdViewerIndexRoute
  '/$runnerId/item/$itemId': typeof RunnerIdDetailsItemItemIdRoute
  '/test/items/details/all': typeof TestItemsDetailsAllRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$runnerId': typeof RunnerIdViewerIndexRoute
  '/edit/$runnerId': typeof EditRunnerIdRoute
  '/gm/encounter-builder': typeof GmEncounterBuilderRoute
  '/gm/initiative-tracker': typeof GmInitiativeTrackerRoute
  '/gm/npc-builder': typeof GmNpcBuilderRoute
  '/gm': typeof GmIndexRoute
  '/new': typeof NewIndexRoute
  '/test': typeof TestIndexRoute
  '/$runnerId/about': typeof RunnerIdViewerAboutRoute
  '/$runnerId/adept-powers': typeof RunnerIdViewerAdeptPowersRoute
  '/$runnerId/complex-forms': typeof RunnerIdViewerComplexFormsRoute
  '/$runnerId/contacts': typeof RunnerIdViewerContactsRoute
  '/$runnerId/defense': typeof RunnerIdViewerDefenseRoute
  '/$runnerId/drones': typeof RunnerIdViewerDronesRoute
  '/$runnerId/finances': typeof RunnerIdViewerFinancesRoute
  '/$runnerId/gear': typeof RunnerIdViewerGearRoute
  '/$runnerId/licenses': typeof RunnerIdViewerLicensesRoute
  '/$runnerId/matrix': typeof RunnerIdViewerMatrixRoute
  '/$runnerId/notes': typeof RunnerIdViewerNotesRoute
  '/$runnerId/offense': typeof RunnerIdViewerOffenseRoute
  '/$runnerId/powers': typeof RunnerIdViewerPowersRoute
  '/$runnerId/skills': typeof RunnerIdViewerSkillsRoute
  '/$runnerId/spells': typeof RunnerIdViewerSpellsRoute
  '/$runnerId/spirits': typeof RunnerIdViewerSpiritsRoute
  '/$runnerId/sprites': typeof RunnerIdViewerSpritesRoute
  '/$runnerId/vehicles': typeof RunnerIdViewerVehiclesRoute
  '/test/entityCard/all': typeof TestEntityCardAllRoute
  '/test/entityCard/migratedItemCards': typeof TestEntityCardMigratedItemCardsRoute
  '/test/theme/typography': typeof TestThemeTypographyRoute
  '/$runnerId/item/$itemId': typeof RunnerIdDetailsItemItemIdRoute
  '/test/items/details/all': typeof TestItemsDetailsAllRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$runnerId': typeof RunnerIdRouteWithChildren
  '/$runnerId/_details': typeof RunnerIdDetailsRouteWithChildren
  '/$runnerId/_viewer': typeof RunnerIdViewerRouteWithChildren
  '/edit/$runnerId': typeof EditRunnerIdRoute
  '/gm/encounter-builder': typeof GmEncounterBuilderRoute
  '/gm/initiative-tracker': typeof GmInitiativeTrackerRoute
  '/gm/npc-builder': typeof GmNpcBuilderRoute
  '/gm/': typeof GmIndexRoute
  '/new/': typeof NewIndexRoute
  '/test/': typeof TestIndexRoute
  '/$runnerId/_viewer/about': typeof RunnerIdViewerAboutRoute
  '/$runnerId/_viewer/adept-powers': typeof RunnerIdViewerAdeptPowersRoute
  '/$runnerId/_viewer/complex-forms': typeof RunnerIdViewerComplexFormsRoute
  '/$runnerId/_viewer/contacts': typeof RunnerIdViewerContactsRoute
  '/$runnerId/_viewer/defense': typeof RunnerIdViewerDefenseRoute
  '/$runnerId/_viewer/drones': typeof RunnerIdViewerDronesRoute
  '/$runnerId/_viewer/finances': typeof RunnerIdViewerFinancesRoute
  '/$runnerId/_viewer/gear': typeof RunnerIdViewerGearRoute
  '/$runnerId/_viewer/licenses': typeof RunnerIdViewerLicensesRoute
  '/$runnerId/_viewer/matrix': typeof RunnerIdViewerMatrixRoute
  '/$runnerId/_viewer/notes': typeof RunnerIdViewerNotesRoute
  '/$runnerId/_viewer/offense': typeof RunnerIdViewerOffenseRoute
  '/$runnerId/_viewer/powers': typeof RunnerIdViewerPowersRoute
  '/$runnerId/_viewer/skills': typeof RunnerIdViewerSkillsRoute
  '/$runnerId/_viewer/spells': typeof RunnerIdViewerSpellsRoute
  '/$runnerId/_viewer/spirits': typeof RunnerIdViewerSpiritsRoute
  '/$runnerId/_viewer/sprites': typeof RunnerIdViewerSpritesRoute
  '/$runnerId/_viewer/vehicles': typeof RunnerIdViewerVehiclesRoute
  '/test/entityCard/all': typeof TestEntityCardAllRoute
  '/test/entityCard/migratedItemCards': typeof TestEntityCardMigratedItemCardsRoute
  '/test/theme/typography': typeof TestThemeTypographyRoute
  '/$runnerId/_viewer/': typeof RunnerIdViewerIndexRoute
  '/$runnerId/_details/item/$itemId': typeof RunnerIdDetailsItemItemIdRoute
  '/test/items/details/all': typeof TestItemsDetailsAllRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$runnerId'
    | '/edit/$runnerId'
    | '/gm/encounter-builder'
    | '/gm/initiative-tracker'
    | '/gm/npc-builder'
    | '/gm/'
    | '/new/'
    | '/test/'
    | '/$runnerId/about'
    | '/$runnerId/adept-powers'
    | '/$runnerId/complex-forms'
    | '/$runnerId/contacts'
    | '/$runnerId/defense'
    | '/$runnerId/drones'
    | '/$runnerId/finances'
    | '/$runnerId/gear'
    | '/$runnerId/licenses'
    | '/$runnerId/matrix'
    | '/$runnerId/notes'
    | '/$runnerId/offense'
    | '/$runnerId/powers'
    | '/$runnerId/skills'
    | '/$runnerId/spells'
    | '/$runnerId/spirits'
    | '/$runnerId/sprites'
    | '/$runnerId/vehicles'
    | '/test/entityCard/all'
    | '/test/entityCard/migratedItemCards'
    | '/test/theme/typography'
    | '/$runnerId/'
    | '/$runnerId/item/$itemId'
    | '/test/items/details/all'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$runnerId'
    | '/edit/$runnerId'
    | '/gm/encounter-builder'
    | '/gm/initiative-tracker'
    | '/gm/npc-builder'
    | '/gm'
    | '/new'
    | '/test'
    | '/$runnerId/about'
    | '/$runnerId/adept-powers'
    | '/$runnerId/complex-forms'
    | '/$runnerId/contacts'
    | '/$runnerId/defense'
    | '/$runnerId/drones'
    | '/$runnerId/finances'
    | '/$runnerId/gear'
    | '/$runnerId/licenses'
    | '/$runnerId/matrix'
    | '/$runnerId/notes'
    | '/$runnerId/offense'
    | '/$runnerId/powers'
    | '/$runnerId/skills'
    | '/$runnerId/spells'
    | '/$runnerId/spirits'
    | '/$runnerId/sprites'
    | '/$runnerId/vehicles'
    | '/test/entityCard/all'
    | '/test/entityCard/migratedItemCards'
    | '/test/theme/typography'
    | '/$runnerId/item/$itemId'
    | '/test/items/details/all'
  id:
    | '__root__'
    | '/'
    | '/$runnerId'
    | '/$runnerId/_details'
    | '/$runnerId/_viewer'
    | '/edit/$runnerId'
    | '/gm/encounter-builder'
    | '/gm/initiative-tracker'
    | '/gm/npc-builder'
    | '/gm/'
    | '/new/'
    | '/test/'
    | '/$runnerId/_viewer/about'
    | '/$runnerId/_viewer/adept-powers'
    | '/$runnerId/_viewer/complex-forms'
    | '/$runnerId/_viewer/contacts'
    | '/$runnerId/_viewer/defense'
    | '/$runnerId/_viewer/drones'
    | '/$runnerId/_viewer/finances'
    | '/$runnerId/_viewer/gear'
    | '/$runnerId/_viewer/licenses'
    | '/$runnerId/_viewer/matrix'
    | '/$runnerId/_viewer/notes'
    | '/$runnerId/_viewer/offense'
    | '/$runnerId/_viewer/powers'
    | '/$runnerId/_viewer/skills'
    | '/$runnerId/_viewer/spells'
    | '/$runnerId/_viewer/spirits'
    | '/$runnerId/_viewer/sprites'
    | '/$runnerId/_viewer/vehicles'
    | '/test/entityCard/all'
    | '/test/entityCard/migratedItemCards'
    | '/test/theme/typography'
    | '/$runnerId/_viewer/'
    | '/$runnerId/_details/item/$itemId'
    | '/test/items/details/all'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RunnerIdRoute: typeof RunnerIdRouteWithChildren
  EditRunnerIdRoute: typeof EditRunnerIdRoute
  GmEncounterBuilderRoute: typeof GmEncounterBuilderRoute
  GmInitiativeTrackerRoute: typeof GmInitiativeTrackerRoute
  GmNpcBuilderRoute: typeof GmNpcBuilderRoute
  GmIndexRoute: typeof GmIndexRoute
  NewIndexRoute: typeof NewIndexRoute
  TestIndexRoute: typeof TestIndexRoute
  TestEntityCardAllRoute: typeof TestEntityCardAllRoute
  TestEntityCardMigratedItemCardsRoute: typeof TestEntityCardMigratedItemCardsRoute
  TestThemeTypographyRoute: typeof TestThemeTypographyRoute
  TestItemsDetailsAllRoute: typeof TestItemsDetailsAllRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$runnerId': {
      id: '/$runnerId'
      path: '/$runnerId'
      fullPath: '/$runnerId'
      preLoaderRoute: typeof RunnerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$runnerId/_details': {
      id: '/$runnerId/_details'
      path: ''
      fullPath: '/$runnerId'
      preLoaderRoute: typeof RunnerIdDetailsRouteImport
      parentRoute: typeof RunnerIdRoute
    }
    '/$runnerId/_viewer': {
      id: '/$runnerId/_viewer'
      path: ''
      fullPath: '/$runnerId'
      preLoaderRoute: typeof RunnerIdViewerRouteImport
      parentRoute: typeof RunnerIdRoute
    }
    '/edit/$runnerId': {
      id: '/edit/$runnerId'
      path: '/edit/$runnerId'
      fullPath: '/edit/$runnerId'
      preLoaderRoute: typeof EditRunnerIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gm/': {
      id: '/gm/'
      path: '/gm'
      fullPath: '/gm/'
      preLoaderRoute: typeof GmIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gm/encounter-builder': {
      id: '/gm/encounter-builder'
      path: '/gm/encounter-builder'
      fullPath: '/gm/encounter-builder'
      preLoaderRoute: typeof GmEncounterBuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gm/initiative-tracker': {
      id: '/gm/initiative-tracker'
      path: '/gm/initiative-tracker'
      fullPath: '/gm/initiative-tracker'
      preLoaderRoute: typeof GmInitiativeTrackerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gm/npc-builder': {
      id: '/gm/npc-builder'
      path: '/gm/npc-builder'
      fullPath: '/gm/npc-builder'
      preLoaderRoute: typeof GmNpcBuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new/': {
      id: '/new/'
      path: '/new'
      fullPath: '/new/'
      preLoaderRoute: typeof NewIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test/': {
      id: '/test/'
      path: '/test'
      fullPath: '/test/'
      preLoaderRoute: typeof TestIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$runnerId/_viewer/': {
      id: '/$runnerId/_viewer/'
      path: '/'
      fullPath: '/$runnerId/'
      preLoaderRoute: typeof RunnerIdViewerIndexRouteImport
      parentRoute: typeof RunnerIdViewerRoute
    }
    '/$runnerId/_viewer/about': {
      id: '/$runnerId/_viewer/about'
      path: '/about'
      fullPath: '/$runnerId/about'
      preLoaderRoute: typeof RunnerIdViewerAboutRouteImport
      parentRoute: typeof RunnerIdViewerRoute
    }
    '/$runnerId/_viewer/adept-powers': {
      id: '/$runnerId/_viewer/adept-powers'
      path: '/adept-powers'
      fullPath: '/$runnerId/adept-powers'
      preLoaderRoute: typeof RunnerIdViewerAdeptPowersRouteImport
      parentRoute: typeof RunnerIdViewerRoute
    }
    '/$runnerId/_viewer/complex-forms': {
      id: '/$runnerId/_viewer/complex-forms'
      path: '/complex-forms'
      fullPath: '/$runnerId/complex-forms'
      preLoaderRoute: typeof RunnerIdViewerComplexFormsRouteImport
      parentRoute: typeof RunnerIdViewerRoute
    }
    '/$runnerId/_viewer/contacts': {
      id: '/$runnerId/_viewer/contacts'
      path: '/contacts'
      fullPath: '/$runnerId/contacts'
      preLoaderRoute: typeof RunnerIdViewerContactsRouteImport
      parentRoute: typeof RunnerIdViewerRoute
    }
    '/$runnerId/_viewer/defense': {
      id: '/$runnerId/_viewer/defense'
      path: '/defense'
      fullPath: '/$runnerId/defense'
      preLoaderRoute: typeof RunnerIdViewerDefenseRouteImport
      parentRoute: typeof RunnerIdViewerRoute
    }
    '/$runnerId/_viewer/drones': {
      id: '/$runnerId/_viewer/drones'
      path: '/drones'
      fullPath: '/$runnerId/drones'
      preLoaderRoute: typeof RunnerIdViewerDronesRouteImport
      parentRoute: typeof RunnerIdViewerRoute
    }
    '/$runnerId/_viewer/finances': {
      id: '/$runnerId/_viewer/finances'
      path: '/finances'
      fullPath: '/$runnerId/finances'
      preLoaderRoute: typeof RunnerIdViewerFinancesRouteImport
      parentRoute: typeof RunnerIdViewerRoute
    }
    '/$runnerId/_viewer/gear': {
      id: '/$runnerId/_viewer/gear'
      path: '/gear'
      fullPath: '/$runnerId/gear'
      preLoaderRoute: typeof RunnerIdViewerGearRouteImport
      parentRoute: typeof RunnerIdViewerRoute
    }
    '/$runnerId/_viewer/licenses': {
      id: '/$runnerId/_viewer/licenses'
      path: '/licenses'
      fullPath: '/$runnerId/licenses'
      preLoaderRoute: typeof RunnerIdViewerLicensesRouteImport
      parentRoute: typeof RunnerIdViewerRoute
    }
    '/$runnerId/_viewer/matrix': {
      id: '/$runnerId/_viewer/matrix'
      path: '/matrix'
      fullPath: '/$runnerId/matrix'
      preLoaderRoute: typeof RunnerIdViewerMatrixRouteImport
      parentRoute: typeof RunnerIdViewerRoute
    }
    '/$runnerId/_viewer/notes': {
      id: '/$runnerId/_viewer/notes'
      path: '/notes'
      fullPath: '/$runnerId/notes'
      preLoaderRoute: typeof RunnerIdViewerNotesRouteImport
      parentRoute: typeof RunnerIdViewerRoute
    }
    '/$runnerId/_viewer/offense': {
      id: '/$runnerId/_viewer/offense'
      path: '/offense'
      fullPath: '/$runnerId/offense'
      preLoaderRoute: typeof RunnerIdViewerOffenseRouteImport
      parentRoute: typeof RunnerIdViewerRoute
    }
    '/$runnerId/_viewer/powers': {
      id: '/$runnerId/_viewer/powers'
      path: '/powers'
      fullPath: '/$runnerId/powers'
      preLoaderRoute: typeof RunnerIdViewerPowersRouteImport
      parentRoute: typeof RunnerIdViewerRoute
    }
    '/$runnerId/_viewer/skills': {
      id: '/$runnerId/_viewer/skills'
      path: '/skills'
      fullPath: '/$runnerId/skills'
      preLoaderRoute: typeof RunnerIdViewerSkillsRouteImport
      parentRoute: typeof RunnerIdViewerRoute
    }
    '/$runnerId/_viewer/spells': {
      id: '/$runnerId/_viewer/spells'
      path: '/spells'
      fullPath: '/$runnerId/spells'
      preLoaderRoute: typeof RunnerIdViewerSpellsRouteImport
      parentRoute: typeof RunnerIdViewerRoute
    }
    '/$runnerId/_viewer/spirits': {
      id: '/$runnerId/_viewer/spirits'
      path: '/spirits'
      fullPath: '/$runnerId/spirits'
      preLoaderRoute: typeof RunnerIdViewerSpiritsRouteImport
      parentRoute: typeof RunnerIdViewerRoute
    }
    '/$runnerId/_viewer/sprites': {
      id: '/$runnerId/_viewer/sprites'
      path: '/sprites'
      fullPath: '/$runnerId/sprites'
      preLoaderRoute: typeof RunnerIdViewerSpritesRouteImport
      parentRoute: typeof RunnerIdViewerRoute
    }
    '/$runnerId/_viewer/vehicles': {
      id: '/$runnerId/_viewer/vehicles'
      path: '/vehicles'
      fullPath: '/$runnerId/vehicles'
      preLoaderRoute: typeof RunnerIdViewerVehiclesRouteImport
      parentRoute: typeof RunnerIdViewerRoute
    }
    '/test/entityCard/all': {
      id: '/test/entityCard/all'
      path: '/test/entityCard/all'
      fullPath: '/test/entityCard/all'
      preLoaderRoute: typeof TestEntityCardAllRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test/entityCard/migratedItemCards': {
      id: '/test/entityCard/migratedItemCards'
      path: '/test/entityCard/migratedItemCards'
      fullPath: '/test/entityCard/migratedItemCards'
      preLoaderRoute: typeof TestEntityCardMigratedItemCardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test/theme/typography': {
      id: '/test/theme/typography'
      path: '/test/theme/typography'
      fullPath: '/test/theme/typography'
      preLoaderRoute: typeof TestThemeTypographyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$runnerId/_details/item/$itemId': {
      id: '/$runnerId/_details/item/$itemId'
      path: '/item/$itemId'
      fullPath: '/$runnerId/item/$itemId'
      preLoaderRoute: typeof RunnerIdDetailsItemItemIdRouteImport
      parentRoute: typeof RunnerIdDetailsRoute
    }
    '/test/items/details/all': {
      id: '/test/items/details/all'
      path: '/test/items/details/all'
      fullPath: '/test/items/details/all'
      preLoaderRoute: typeof TestItemsDetailsAllRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface RunnerIdDetailsRouteChildren {
  RunnerIdDetailsItemItemIdRoute: typeof RunnerIdDetailsItemItemIdRoute
}

const RunnerIdDetailsRouteChildren: RunnerIdDetailsRouteChildren = {
  RunnerIdDetailsItemItemIdRoute: RunnerIdDetailsItemItemIdRoute,
}

const RunnerIdDetailsRouteWithChildren = RunnerIdDetailsRoute._addFileChildren(
  RunnerIdDetailsRouteChildren,
)

interface RunnerIdViewerRouteChildren {
  RunnerIdViewerAboutRoute: typeof RunnerIdViewerAboutRoute
  RunnerIdViewerAdeptPowersRoute: typeof RunnerIdViewerAdeptPowersRoute
  RunnerIdViewerComplexFormsRoute: typeof RunnerIdViewerComplexFormsRoute
  RunnerIdViewerContactsRoute: typeof RunnerIdViewerContactsRoute
  RunnerIdViewerDefenseRoute: typeof RunnerIdViewerDefenseRoute
  RunnerIdViewerDronesRoute: typeof RunnerIdViewerDronesRoute
  RunnerIdViewerFinancesRoute: typeof RunnerIdViewerFinancesRoute
  RunnerIdViewerGearRoute: typeof RunnerIdViewerGearRoute
  RunnerIdViewerLicensesRoute: typeof RunnerIdViewerLicensesRoute
  RunnerIdViewerMatrixRoute: typeof RunnerIdViewerMatrixRoute
  RunnerIdViewerNotesRoute: typeof RunnerIdViewerNotesRoute
  RunnerIdViewerOffenseRoute: typeof RunnerIdViewerOffenseRoute
  RunnerIdViewerPowersRoute: typeof RunnerIdViewerPowersRoute
  RunnerIdViewerSkillsRoute: typeof RunnerIdViewerSkillsRoute
  RunnerIdViewerSpellsRoute: typeof RunnerIdViewerSpellsRoute
  RunnerIdViewerSpiritsRoute: typeof RunnerIdViewerSpiritsRoute
  RunnerIdViewerSpritesRoute: typeof RunnerIdViewerSpritesRoute
  RunnerIdViewerVehiclesRoute: typeof RunnerIdViewerVehiclesRoute
  RunnerIdViewerIndexRoute: typeof RunnerIdViewerIndexRoute
}

const RunnerIdViewerRouteChildren: RunnerIdViewerRouteChildren = {
  RunnerIdViewerAboutRoute: RunnerIdViewerAboutRoute,
  RunnerIdViewerAdeptPowersRoute: RunnerIdViewerAdeptPowersRoute,
  RunnerIdViewerComplexFormsRoute: RunnerIdViewerComplexFormsRoute,
  RunnerIdViewerContactsRoute: RunnerIdViewerContactsRoute,
  RunnerIdViewerDefenseRoute: RunnerIdViewerDefenseRoute,
  RunnerIdViewerDronesRoute: RunnerIdViewerDronesRoute,
  RunnerIdViewerFinancesRoute: RunnerIdViewerFinancesRoute,
  RunnerIdViewerGearRoute: RunnerIdViewerGearRoute,
  RunnerIdViewerLicensesRoute: RunnerIdViewerLicensesRoute,
  RunnerIdViewerMatrixRoute: RunnerIdViewerMatrixRoute,
  RunnerIdViewerNotesRoute: RunnerIdViewerNotesRoute,
  RunnerIdViewerOffenseRoute: RunnerIdViewerOffenseRoute,
  RunnerIdViewerPowersRoute: RunnerIdViewerPowersRoute,
  RunnerIdViewerSkillsRoute: RunnerIdViewerSkillsRoute,
  RunnerIdViewerSpellsRoute: RunnerIdViewerSpellsRoute,
  RunnerIdViewerSpiritsRoute: RunnerIdViewerSpiritsRoute,
  RunnerIdViewerSpritesRoute: RunnerIdViewerSpritesRoute,
  RunnerIdViewerVehiclesRoute: RunnerIdViewerVehiclesRoute,
  RunnerIdViewerIndexRoute: RunnerIdViewerIndexRoute,
}

const RunnerIdViewerRouteWithChildren = RunnerIdViewerRoute._addFileChildren(
  RunnerIdViewerRouteChildren,
)

interface RunnerIdRouteChildren {
  RunnerIdDetailsRoute: typeof RunnerIdDetailsRouteWithChildren
  RunnerIdViewerRoute: typeof RunnerIdViewerRouteWithChildren
}

const RunnerIdRouteChildren: RunnerIdRouteChildren = {
  RunnerIdDetailsRoute: RunnerIdDetailsRouteWithChildren,
  RunnerIdViewerRoute: RunnerIdViewerRouteWithChildren,
}

const RunnerIdRouteWithChildren = RunnerIdRoute._addFileChildren(
  RunnerIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RunnerIdRoute: RunnerIdRouteWithChildren,
  EditRunnerIdRoute: EditRunnerIdRoute,
  GmEncounterBuilderRoute: GmEncounterBuilderRoute,
  GmInitiativeTrackerRoute: GmInitiativeTrackerRoute,
  GmNpcBuilderRoute: GmNpcBuilderRoute,
  GmIndexRoute: GmIndexRoute,
  NewIndexRoute: NewIndexRoute,
  TestIndexRoute: TestIndexRoute,
  TestEntityCardAllRoute: TestEntityCardAllRoute,
  TestEntityCardMigratedItemCardsRoute: TestEntityCardMigratedItemCardsRoute,
  TestThemeTypographyRoute: TestThemeTypographyRoute,
  TestItemsDetailsAllRoute: TestItemsDetailsAllRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
